name: cnc_flutter_app
description: CNC user application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  encrypt: ^5.0.0
  carousel_slider: ^4.0.0
  clipboard: ^0.1.3
  equatable: ^2.0.3
  fl_chart: ^0.36.2
  flutter_slidable: ^0.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_speed_dial: ^3.0.5
  #  flutter_speed_dial_material_design: ^2.0.0
  flutter_svg: ^0.22.0
  fraction: ^3.0.1
  flutter_picker:
  font_awesome_flutter: ^9.1.0
  http: ^0.13.3
  material_design_icons_flutter: ^5.0.5955-rc.1
  path_drawing: ^0.5.1
  percent_indicator: ^3.0.1
  scrolling_day_calendar:
    git: https://github.com/ritvij14/scrolling-day-calendar.git
  share: ^2.0.4
  shared_preferences: ^2.0.6
  sticky_grouped_list:
    git:
      url: https://github.com/ritvij14/sticky_grouped_list.git
      ref: feature/null-safety
  syncfusion_flutter_pdf: ^19.2.44-beta
  syncfusion_flutter_pdfviewer: ^19.2.44-beta
  table_calendar: ^3.0.1
  url_launcher: ^6.0.8
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  flutter_redux: ^0.8.2
  grouped_list: ^4.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  confetti: ^0.6.0-nullsafety
  flutter_local_notifications: ^9.5.3+1
  flutter_login: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/badge1.png
    - assets/images/badge2.png
    - assets/images/badge3.png
    - assets/placeholder_logo.png
    - assets/logo.png
    - assets/
    - assets/images/popcat.jpg
    - assets/icons/Accessibility New.svg
    - assets/icons/Bell.svg
    - assets/icons/Calendar.svg
    - assets/icons/Camera Icon.svg
    - assets/icons/Email.svg
    - assets/icons/Log out.svg
    - assets/icons/Phone.svg
    - assets/icons/Settings.svg
    - assets/icons/User Icon.svg
    - assets/icons/Weight.svg
    - assets/images/activityBadge1.png
    - assets/images/activityBadge2.png
    - assets/images/activityBadge3.png
    - assets/images/dairyBadge1.png
    - assets/images/dairyBadge2.png
    - assets/images/dairyBadge3.png
    - assets/images/drinkBadge1.png
    - assets/images/drinkBadge2.png
    - assets/images/drinkBadge3.png
    - assets/images/fruitBadge1.png
    - assets/images/fruitBadge2.png
    - assets/images/fruitBadge3.png
    - assets/images/grainBadge1.png
    - assets/images/grainBadge2.png
    - assets/images/grainBadge3.png
    - assets/images/proteinBadge1.png
    - assets/images/proteinBadge2.png
    - assets/images/proteinBadge3.png
    - assets/images/snackBadge1.png
    - assets/images/snackBadge2.png
    - assets/images/snackBadge3.png
    - assets/images/vegetableBadge1.png
    - assets/images/vegetableBadge2.png
    - assets/images/vegetableBadge3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
